name: Deploy App1 to EKS

on:
  push:
    branches:
      - main  # Cambia a la rama que prefieras

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub (o Amazon ECR)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/app1:latest .
        docker push your-dockerhub-username/app1:latest

    # Configure kubectl to use the cluster
    - name: Set up kubectl
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-west-2 --name devops-test-cluster

    # Deploy to EKS
    - name: Deploy App1 to EKS
      run: |
        kubectl apply -f app1-deployment.yaml